### ISSUE TITLE
What is a collaborators role in your project?

### ISSUE THREAD

**Issue by ghost** [antfarmar/Unity-3D-Asteroids#23]
As a collaborator, I am happy to join development of this exciting project. 

As a collaborator, what is expected of me? 
How can I chip in without being an annoyance?

For me specifically, I would be interested in any of the 4 following activities:
- Reviewing commits, flagging potential issues
  - Performance
  - Maintainability
  - Readability
  - Bad practices
  - _Risks feeling nagged?_
- Cleaning up, [make code read like a prose](http://musingstudio.com/2013/02/11/software-code-should-read-like-well-written-prose/)
  - Provide _practical_ reason
  - Small pull requests
  - Avoid merge conflicts
  - _Risks feeling pointless effort?_
- Work toward completing [open issues](https://github.com/antfarmar/Unity-3D-Asteroids/issues)
  - Implement a simple solution to any issue
  - Submit pull request
  - Avoid merge conflicts
  - _Risks feeling lost ownership?_
- Unit and integration tests ([Unity Test Tools](https://www.assetstore.unity3d.com/en/#!/content/13802))
  - Explore testing for games
    - Past experience: Inherently hard
    - What causes it to be hard?
    - How to make it easier?
    - What _practical_ value gained from it?
  - Start with high risk areas
    - Basis for bug-fixes
    - Screen wrapping?
  - Could start in separate branch to test waters
  - _Risks feeling slogged down?_
  - _Risks feeling too much information?_
  - _Risks feeling too much for small project?_

What do you feel? If you feel any of the points above is redundant, let's drop them. The secondary bullet points are examples of things to consider - not hard rules. The point is to get something going which we both feel provide some value for the time spent. Also, no hard feelings if you want to try something out, later find out it's a nightmare to collab and want to cancel it. I want you to always feel you are in control, so please speak your frank mind.

Do you have other suggestions? What would _you_ feel would be _fun_ to do together?

**Comment by antfarmar** [comment]
> How can I chip in without being an annoyance?

Don't worry about this. Feel free to speak your mind when and where you want. I'm easy.

You clearly have more experience with Unity\design\C# than I do, so I appreciate your feedback.
This project just started out as a little experiment with no real expectations or firm end goal, so I'm figuring it out as I go along too. I'm just trying to document it all as it progresses.

But as I've said before, my original intention was to get a base playable game (with no real design), then constantly refactor it into different branches, each strictly focused on a specific design pattern (e.g. UnityEvents messaging). So ultimately there would be the exact same game on different branches, but each would be implemented differently, as it uses a different pattern implementation.

We'll see.
