### ISSUE TITLE
Bullets Could Inherit Ship's Velocity

### ISSUE THREAD

**Issue by antfarmar** [antfarmar/Unity-3D-Asteroids#35]
##### Problem
- Bullets currently don't inherit the ship's velocity when fired.
- With a thrust powerup, the ship is almost as fast as bullets.
- Hence, bullets barely escape the ship's nozzle.
- Velocity inheritance would also be more physically realistic.
##### Possible Fixes
- Does the  `Rigidbody` API have any simple functions for this?

**Comment by ghost** [comment]
https://github.com/antfarmar/Unity-3D-Asteroids/blob/b9c0cbda61f6442a558a2b94945409720f054d78/Assets/Asteroids/Scripts/MicroBehaviours/ShipShooter.cs#L88-L93

Add the velocity of the rigidbody to the bullet.
And get rid of those comments I placed there while you are at it :)

```
Bullet().Fire(nozzle.position, nozzle.rotation, direction * velocity + rb.velocity);
```

**Comment by antfarmar** [comment]
Oh yeah, vector addition. Who knew rigidbodies had a velocity property? :laughing:
I also renamed the variables to distinguish scalars from vectors.

Commit a56a4ed

``` csharp
void FireBullet(Vector3 direction, float speedScalar = bulletSpeed)
{
        direction = (direction * speedScalar) + rbody.velocity;
        Bullet().Fire(nozzle.position, nozzle.rotation, direction);
}
```

Could probably also just collapse those 2 parameters to simply velocity and have the caller do the math.
