### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by TimTinkers** [antfarmar/Unity-3D-Asteroids#40]
Hello @antfarmar -- great project you've got here! This has been a really valuable resource for learning Unity. Do you think you'd ever consider specifying a software license to permit the reuse of your code or assets in other projects? Perhaps something like the MIT license?

Even if you don't want to permit reuse or open source this project as such, I think specifying a license to clarify your stance here would be desirable.

**Comment by antfarmar** [comment]
Hi Tim.
Thanks for the kind words!
Added the MIT license. Reuse away!
Cheers.
